name: Clean Package
on:
    push:
        branches:
            - "main"
jobs:
    First-Job:
        name: Before Checkout
        runs-on: ubuntu-latest
        steps: 
            - name: beforecheckout
              run: ls
              shell: bash
            - name: checkoutactions
              uses: actions/checkout@v4
            - name: aftercheckout
              run: ls
              shell: bash
            - name: Run Maven
              run: mvn clean package
              shell: bash





